
/*------------------------ Models ------------------------*/

resource.AddFile( "models/weapons/v_fists.mdl" )
resource.AddFile( "models/weapons/w_fists.mdl" )
resource.AddFile( "models/weapons/v_shovel.mdl" )
resource.AddFile( "models/weapons/w_shovel.mdl" )
resource.AddFile( "models/weapons/v_copper_pickaxe.mdl" )
resource.AddFile( "models/weapons/w_copper_pickaxe.mdl" )
resource.AddFile( "models/weapons/v_iron_pickaxe.mdl" )
resource.AddFile( "models/weapons/w_iron_pickaxe.mdl" )
resource.AddFile( "models/weapons/v_stone_pickaxe.mdl" )
resource.AddFile( "models/weapons/w_stone_pickaxe.mdl" )
resource.AddFile( "models/weapons/v_copper_hatchet.mdl" )
resource.AddFile( "models/weapons/v_iron_hatchet.mdl" )
resource.AddFile( "models/weapons/v_stone_hatchet.mdl" )
resource.AddFile( "models/weapons/w_copper_hatchet.mdl" )
resource.AddFile( "models/weapons/w_iron_hatchet.mdl" )
resource.AddFile( "models/weapons/w_stone_hatchet.mdl" )

resource.AddFile( "models/gm_forest/tree_oak1.mdl" )

/*------------------------ Materials ------------------------*/

resource.AddFile( "materials/models/weapons/shovel/shovel1.vmt" )
resource.AddFile( "materials/models/weapons/shovel/shovel1.vtf" )
resource.AddFile( "materials/models/weapons/shovel/shovel1_n.vtf" )
resource.AddFile( "materials/models/weapons/shovel/shovel2.vmt" )
resource.AddFile( "materials/models/weapons/shovel/shovel2.vtf" )
resource.AddFile( "materials/models/weapons/shovel/shovel2_n.vtf" )
resource.AddFile( "materials/models/weapons/shovel/shovel3.vmt" )
resource.AddFile( "materials/models/weapons/shovel/shovel3.vtf" )
resource.AddFile( "materials/models/weapons/shovel/shovel3_n.vtf" )
resource.AddFile( "materials/models/weapons/pickaxe/copper/copper.vtf" )
resource.AddFile( "materials/models/weapons/pickaxe/copper/copper_n.vtf" )
resource.AddFile( "materials/models/weapons/pickaxe/copper/pickaxe01.vmt" )
resource.AddFile( "materials/models/weapons/pickaxe/stone/pickaxe01.vmt" )
resource.AddFile( "materials/models/weapons/pickaxe/stone/stone.vtf" )
resource.AddFile( "materials/models/weapons/pickaxe/stone/stone_n.vtf" )
resource.AddFile( "materials/models/weapons/pickaxe/iron/iron.vtf" )
resource.AddFile( "materials/models/weapons/pickaxe/iron/iron_n.vtf" )
resource.AddFile( "materials/models/weapons/pickaxe/iron/pickaxe01.vmt" )
resource.AddFile( "materials/models/weapons/hatchet/copper/axe.vmt" )
resource.AddFile( "materials/models/weapons/hatchet/copper/Copper.vtf" )
resource.AddFile( "materials/models/weapons/hatchet/copper/Copper_n.vtf" )
resource.AddFile( "materials/models/weapons/hatchet/stone/axe.vmt" )
resource.AddFile( "materials/models/weapons/hatchet/stone/stone.vtf" )
resource.AddFile( "materials/models/weapons/hatchet/stone/stone_n.vtf" )
resource.AddFile( "materials/models/weapons/hatchet/iron/axe.vmt" )
resource.AddFile( "materials/models/weapons/hatchet/iron/iron.vtf" )
resource.AddFile( "materials/models/weapons/hatchet/iron/iron_n.vtf" )
resource.AddFile( "materials/models/weapons/hands.vmt" )
resource.AddFile( "materials/models/weapons/hands.vtf" )
resource.AddFile( "materials/models/weapons/hands_normal.vtf" )

resource.AddFile( "materials/gm_forest/oak_brk.vmt" )
resource.AddFile( "materials/gm_forest/brg_eik_brn2.vmt" )
resource.AddFile( "materials/gm_forest/brg_eik_brn2.vtf" )

/*------------------------ Sounds ------------------------*/

resource.AddFile( "sound/citizen_beaten1.wav" )
resource.AddFile( "sound/citizen_beaten4.wav" )
resource.AddFile( "sound/citizen_beaten5.wav" )
resource.AddFile( "sound/cough1.wav" )
resource.AddFile( "sound/cough2.wav" )
resource.AddFile( "sound/cough3.wav" )
resource.AddFile( "sound/cough4.wav" )
